version: 2.1

references:
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

executors:
  doc_builder:
    docker:
      - image: mbed/doc_builder:os-welcome-styles-1133
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS

commands:
  setup_aws_credentials:
    description: "Setup AWS credentials"
    steps:
      - run:
          name: Write credentials to ~/.aws/credentials
          command: |
            mkdir ~/.aws
            echo -e "[default]\naws_access_key_id=$AWS_PROD_ACCESS_KEY_ID\naws_secret_access_key=$AWS_PROD_SECRET_KEY\n" > ~/.aws/credentials
  write_env_variables:
    description: "Write ENV variables"
    steps:
      - run:
          command: |
            echo "export CIRCLE_BRANCH_NO_SLASH=$(echo $CIRCLE_BRANCH|sed 's/\//-/')" >> /tmp/env


jobs:
  build:
    executor: doc_builder
    steps:
      - checkout
      - setup_aws_credentials
      - write_env_variables
      - run:
          name: Validate and build documentation
          command: |
            source /tmp/env
            docbuilder build $CIRCLE_BRANCH_NO_SLASH /tmp/workspace/artifacts --path ~/project/docs.json --github_token "$GITHUB_TOKEN"
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - artifacts

  publish_to_s3:
    executor: doc_builder
    steps:
      - setup_aws_credentials
      - write_env_variables
      - *attach_workspace
      - run:
          name: Upload documentation to s3
          command: |
            source /tmp/env
            docbuilder publish /tmp/workspace/artifacts/$CIRCLE_BRANCH_NO_SLASH iot-doc-builds $CIRCLE_PROJECT_REPONAME/$CIRCLE_BRANCH_NO_SLASH/$CIRCLE_SHA1

  zip_documentation:
    machine: true
    steps:
      - *attach_workspace
      - run:
          name: Zip built documentation
          command: |
            cd /tmp/workspace/artifacts
            zip -r /tmp/workspace/docs.zip .
      - store_artifacts:
          path: /tmp/workspace/docs.zip

  make_live:
    executor: doc_builder
    steps:
      - setup_aws_credentials
      - write_env_variables
      - run:
          name: Update live version on s3
          command: |
            source /tmp/env
            docbuilder set_live_version iot-doc-builds $CIRCLE_PROJECT_REPONAME/$CIRCLE_BRANCH_NO_SLASH/$CIRCLE_SHA1

workflows:
  version: 2
  build-publish-zip-deploy:
    jobs:
      - build
      - publish_to_s3:
          requires:
            - build
      - zip_documentation:
          requires:
            - build
#       - await_approval:
#           type: approval
#           requires:
#             - publish_to_s3
      - make_live:
          requires:
#             - await_approval
            - publish_to_s3
